services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your-secret-api-key
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - redis-cache

  redis-cache:
    image: redis
    ports:
      - "6380:6379"